[package]
name = "simplerusthttpsclient"
version = "0.0.2"
edition = "2021"

authors = ["Dario Caruso"]
description = "simple rust client with rust native tls"
license = "Apache-2.0"
documentation = "https://docs.rs/simplerusthttpsclient"
repository = "https://github.com/dottgonzo/simplerusthttpsclient"



[dependencies]
reqwest = { version = "0.11.22", default-features = false, features = ["rustls-tls","json","multipart"] }
url = "2.4.1"
tokio = { version = "1.33.0", features = ["macros"] }
rustls = { version = "0.21.8", features = [
    "dangerous_configuration",
    "secret_extraction",
] }
rustls-pemfile = "1.0.3"
anyhow = "1.0.75"
serde = { version = "1.0.190", features = ["derive", "rc"] }
tokio-util = "0.7.10"

